platform: linux

image_resource:
  type: docker-image
  source:
    repository:
      teliaoss/concourse-awscli

params:
  directory:

inputs:
  - name: source
  - name: terraform-out-init

outputs:
  - name: secret-source

run:
  path: source/.ci/tasks/inject-arns/task.sh