jobs:
  - name: test-default
    plan:
      - aggregate:
        - get: this-module
          trigger: true
      - task: inject-secrets
        params:
          directory: default/init
          AWS_ACCOUNT_ID: ((telia-divx-common-services-stage-account-id))
          KMS_KEY_ID: ((telia-divx-common-services-stage-state-bucket-key))
        file: this-module/.ci/tasks/inject-secrets/task.yml
        input_mapping: {source: this-module}
        output_mapping: {secret-source: init-source}
      - task: apply-init
        params:
          directory: default/init
          AWS_ACCESS_KEY_ID: ((telia-divx-common-services-stage-access-key))
          AWS_SECRET_ACCESS_KEY: ((telia-divx-common-services-stage-secret-key))
          AWS_SESSION_TOKEN: ((telia-divx-common-services-stage-session-token))
        file: this-module/.ci/tasks/apply/task.yml
        input_mapping: {source: init-source}
        output_mapping: {terraform-out: terraform-out-init}
      - task: inject-secrets
        params:
          directory: default
          AWS_ACCOUNT_ID: ((telia-divx-common-services-stage-account-id))
          KMS_KEY_ID: ((telia-divx-common-services-stage-state-bucket-key))
          ROUTE53_ZONE: ((testing-pipeline-hosted-zone))
        file: this-module/.ci/tasks/inject-secrets/task.yml
        input_mapping: {source: this-module}
        output_mapping: {secret-source: source}
      - task: inject-arns
        params:
          directory: default
        file: this-module/.ci/tasks/inject-arns/task.yml
        input_mapping: {source: this-module}
        output_mapping: {secret-source: source}
      - task: apply
        params:
          directory: default
          AWS_ACCESS_KEY_ID: ((telia-divx-common-services-stage-access-key))
          AWS_SECRET_ACCESS_KEY: ((telia-divx-common-services-stage-secret-key))
          AWS_SESSION_TOKEN: ((telia-divx-common-services-stage-session-token))
        file: this-module/.ci/tasks/apply/task.yml
        input_mapping: {source: this-module}
      - task: test
        params:
          directory: default
          AWS_ACCESS_KEY_ID: ((telia-divx-common-services-stage-access-key))
          AWS_SECRET_ACCESS_KEY: ((telia-divx-common-services-stage-secret-key))
          AWS_SESSION_TOKEN: ((telia-divx-common-services-stage-session-token))
        file: this-module/.ci/tasks/test/task.yml
      - task: destroy
        params:
          directory: default
          AWS_ACCESS_KEY_ID: ((telia-divx-common-services-stage-access-key))
          AWS_SECRET_ACCESS_KEY: ((telia-divx-common-services-stage-secret-key))
          AWS_SESSION_TOKEN: ((telia-divx-common-services-stage-session-token))
        file: this-module/.ci/tasks/destroy/task.yml

resources:
  - name: this-module
    type: git
    source:
      uri: git@github.com:telia-oss/terraform-aws-sonarqube.git
      branch: testing-pipeline
      private_key: ((aws-common-services-deploy-key))

